### PR TITLE
Adding Base Url support

### PR DESCRIPTION
**Pull request by RePeet13**
Fixes issue #60 by adding a base_url variable, as well as updating every api call with it prepended. Let me know if I missed any calls that need to have it, I tested the main functionality and that worked beautifully.

### CODE REVIEW

**Comment by RePeet13** [comment]
@danielperna84 I looked at the results and it just says trailing whitespace, so I'll fix and commit that here as well

**Comment by danielperna84** [comment]
Thanks for your work. Didn't think about that.

What I would change:
1. For the JavaScript part, instead of substituting the `base_url` when rendering the template, I'd rather do that 100% in JavaScript. For example:
```javascript
$.get(encodeURI("${base_url}api/listdir?path=" + path), function(data)
```
would become
```javascript
$.get(encodeURI(window.location.pathname + "api/listdir?path=" + path), function(data)
```
I haven't tested that obviously, but I think that should work and would take a little load off the server process when initially rendering the template. Additionally changes on the backend won't break this.

2. For the Python part I think a more generic way could be to instead of
```python
if req.path == '/' + BASE_URL + 'api/file':
```
do
```python
if req.path.endswith('api/file'):
```
That would make the setting for the base URL obsolete (if it works how I would expect it to work).

These two changes combined would presumably expose the same functionality without anyone touching their configs. And being automatic people won't enter invalid data. On top of that, the same configurator could run behind different rev-proxies with different paths. Which is rather unlikely, but covering all kinds of setups with a single solution might be worth the change. What do you think?

**Comment by RePeet13** [comment]
Sounds pretty good to me, I could probably code that pretty easily. However I have a few counter questions:
I tried it real quick, and it looks like `window.location.pathname` could return both `ha_configurator` and `ha_configurator/` for the same looking page depending on whether or not the trailing slash is in there. Is there an easy way in javascript to have that whether or not it is in there already?

Secondly, I don't recall what req.path returns, does it include a possible query string?

Lastly, I noticed some behavior that looked like either browser or server caching of files (I am reverse proxying through a caddy server, basic config). After setting up the reverse proxy, I've noticed that sometimes after editing a file, I go back to it and the changes are not present. But going to the file on the fs reveals the changes in tact. Any thoughts on that?
If it was caching, we could possibly circumvent it by tacking on a timestamp in the query string and just ignore it.

**Comment by RePeet13** [comment]
Could to a simple test like
```
( window.location.pathname.charAt(window.location.pathname.length - 1) == '/' ? window.location.pathname : window.location.pathname + '/'
```
Which could be cleaned up, or put in a function, or something..

**Comment by danielperna84** [comment]
1. Shouldn't the slash be there always? I know in Apache the forwards are configured with a trailing slash (and others should do that as well). So when accessing and being forwarded, the slashes should be there. And once the page has loaded it will always stay there since everything else is Ajax. I would just try if it works. If it really becomes a problem it could be changed. But in my opinion just using the `location.window.pathname` should do the job. If it doesn't, the proxy should be tweaked to behave correctly.
2. No, it doesen't. Otherwise all the comparisons that are done wouldn't work either. It's always `==`, which would break if query-parameters were included.
3. No, I don't know what the problem is in this case. However, that to me seems like an edge case where the problem is not within the app but the proxy instead. The configurator does not cache anything. The only server-side approacht that seems acceptable would be to try sending some HTTP headers that control cache behavior in the browser (which the proxy might pick up). Everything else would just be a hack to work around caching imposed by a third party.

**Comment by danielperna84** [comment]
Any news on this?

**Comment by RePeet13** [comment]
Hey! sorry, work and family gatherings took up more time than expected. I'm fine deferring to wisdom about trailing slashes, I just saw the slash, and decided to try it without the slash to see what happened. Are you going to go ahead with your proposed change, or should I, or is this overcome by events (got fixed elsewhere)?

**Comment by RePeet13** [comment]
This was fixed with Daniel's method in 6c81687

**Comment by mason-xx** [comment]
I was looking for that option, but can't find it in the current version.. did I miss something or am I just stupid?

**Pull request closed without merging**
