### PR TITLE
New version

### PR DESCRIPTION
**Pull request by danielperna84**
- Fixed incorrect numeric state option
- Removed check config option (HASS has changed, not useful anymore)
- Added reload for groups and automations
- Proper logging on the server side (useful for supervisor usage)

@jmart518 
Do you mind testing if everythin is working for you? The check configuration option is commented out because apparantly HASS has some changes in the API, which makes the check is pretty much useless now.

### CODE REVIEW

**Comment by jmart518** [comment]
Sure thing, I'll load it up today and report back

**Comment by jmart518** [comment]
So I recently rebuilt my HA and hadn't gotten around to configuring configurator.  I am now running into a strange issue that I hadn't encountered before.  This is definitely not related to any of your new changes, these are with my original working files
The error I'm seeing is:
`Starting server
Listening on: http://0.0.0.0:3218
192.168.26.1 - - [24/Apr/2017 21:10:30] code 400, message Bad request version ('\x9a\x9aÀ+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
192.168.26.1 - - [24/Apr/2017 21:10:30] "ÅÁ¥¨Qï¬¸ý$¤jJOâ¿êZ¦â+§ßïTÀ+À/À,À0Ì©Ì¨ÀÀ/5" 400 -
^CGot signal: 2. Shutting down server`
Any ideas?

**Comment by danielperna84** [comment]
That's odd. It seems as if your client machine is sending its requests using some freaky encoding. Have you tried accessing the configurator using a different device?

**Comment by jmart518** [comment]
Here's the output from a different device:
`Starting server Listening on: http://0.0.0.0:3218
192.168.26.1 - - [25/Apr/2017 10:21:45] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00Å\x01\x00\x00Á\x03\x03\x82\x9dc\x90¶S\x82%ê\x83\x19CúèÖOÔv\x14¨®úR$\xad£r-çoe\x88\x00\x00')
192.168.26.1 - - [25/Apr/2017 10:21:45] "ÅÁc¶S%êCúèÖOÔv¨®úR$­£r-çoeÌ©Ì¨À+À/À,À0ÀÀ/5" 400 -
192.168.26.1 - - [25/Apr/2017 10:21:45] code 400, message Bad request version ('JJÌ©Ì¨À+À/À,À0À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
192.168.26.1 - - [25/Apr/2017 10:21:45] "ÅÁ@ÚÀkyZS!¤réUR`9kJ§ñ®f`Ø¯¢JJÌ©Ì¨À+À/À,À0ÀÀ/5" 400 -`

Very strange stuff

**Comment by danielperna84** [comment]
Since it's a new setup you have, could it be you don't have SSL set up, but still try to access via https?

**Comment by jmart518** [comment]
That was my thought at first too, but SSL is one of the first things I configured on my rebuild

**Comment by jmart518** [comment]
Mystery solved!  I forgot to include my `settings.conf` in my systemd service . . . whoops

Updating with your latest changes now and will report back

**Comment by danielperna84** [comment]
Any news on this?

**Comment by jmart518** [comment]
Great job, everything is working as it should

**Pull request merged**
