### PR TITLE
Fixes for Event Observer

### PR DESCRIPTION
**Pull request by jmart518**
Changed label color to match the rest of the theme
Added label and icon
Possible solution #1 for textarea (Untested)
Changed modal footer to "fixed"

### CODE REVIEW

**Comment by danielperna84** [comment]
Unfortunately not a fix. Somehow the change converts the textarea into a regular input element. The problem with that is, that it's not possible to scroll. Scrolling is very important though because there can be a lot of data. The bigger font also reduces the viewable content.
If there's a way to keep the regular textarea-element, I would prefer that. This is not a function that has to look beautiful. It has to show as much data as possible.

For reference:
Before:
observer-before

After:
observer

**Comment by jmart518** [comment]
Hmm very strange, you can scroll when manually adding text to the textarea.  So that breaks when the data is imported in?

**Comment by jmart518** [comment]
screen shot 2018-04-23 at 12 44 01 pm
screen shot 2018-04-23 at 12 44 08 pm
screen shot 2018-04-23 at 12 44 18 pm

**Comment by danielperna84** [comment]
Got it. Add `$('#ws_events').trigger('autoresize');` below the JavaScript line 2049 (`document.getElementById("ws_events").value = str + "\n\n" + document.getElementById("ws_events").value;`)

And I think the label for the textarea should be removed. It only moves out of the element when the element is active, which isn't necessarily the case for us when people just look at the events without ever clicking the element.

**Pull request merged**
