### PR TITLE
Added simple material icons modal

### PR DESCRIPTION
**Pull request by jmart518**
One less reason to leave configurator

### CODE REVIEW

**Comment by danielperna84** [comment]
At https://materialdesignicons.com/ they have an icon for git. Does that one work now with the changes you've made? The current symbol is more of a placeholder since with the old icon pack there was no icon for git.

**Comment by danielperna84** [comment]
I'm confused. I'm seeing you're using a hosted git-icon now. So we're still not using the icons at https://materialdesignicons.com/, but instead the ones from https://material.io/icons/, which materialize uses in form of a font. Reading through the [docs](https://materialdesignicons.com/getting-started) also makes clear, that they don't host the font via CDN.
To keep everything correct, the link would have to be the second one, with the icon for git now being an exception.

**Comment by danielperna84** [comment]
I now have added the git-icon to the menu on the left, which was what I meant originally. On top of that it's not an image anymore in the about modal as well. However, the card needs some stly fixing now because with the fontbased icon the height of the div is messed up. I bet you know a fix for that! :D
Besides that it's looking great. At first I though we wouldn't need the link to the material icons in the menu on the right. But then I rembered, that the icons in HASS are the same ones, so it makes sense having quick access to those. Great idea! :)

**Comment by jmart518** [comment]
Ah I see now, looks much better!

For the About modal, the easiest way to handle that will be to still use an image instead of a font.  The way that card works, it will probably always act a little strange if we try and force a font.

**Comment by danielperna84** [comment]
Ok. I just noticed, that the old git-image was pixelated. At least for me. That's why I went with the font-icon. But it looks good now.
I now also changed the filebrowser icons to be the ones from the new material icons we use. Because of that the icons now all have the general file-apperance, with the content-indicator within that frame. So it now looks more like one would expect.

**Comment by jmart518** [comment]
I had swapped out that old image (48px) for a higher res (256px)

Just pushed a fix for the top padding on the new filebrowser icons.  That font has a slight difference in padding

Things are looking much more polished with the use of these new icons

**Comment by danielperna84** [comment]
Is there anything else you want to add, or can I merge this and make a new version? :)

**Comment by jmart518** [comment]
I can't think of anything else, let her fly!

**Pull request merged**
