### PR TITLE
File Filtering

### PR DESCRIPTION
**Pull request by sytone**
To keep the UI cleaner I have implemented a simple filter to remove items that match the ignore list.

### CODE REVIEW

**Comment by danielperna84** [comment]
Thanks. I'll have a look at it tomorrow. :)
Although just from reading the description: wouldn't it make more sense the other way around? So instead of excluding certain elements only include the ones that match the filter? Sort of like `ls -l | grep conf`.

**Comment by sytone** [comment]
I thought of that but then if I want to add a new file I have to add it to the list. Where as with the exclusion I expect to have it hidden by default.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by danielperna84** [comment]
I've had a look at it now. I misunderstood what your change would be doing. I though of this being an UI-feature somehow. Anyways, I'm basically fine with that approach. However, it currently would ship with your defaults, which shouldn't be the case.
My suggestion: do for `IGNORE_PATTERN` what I have done for other options like the `ALLOWED_NETWORKS`. Initialize `IGNORE_PATTERN` as an empty list and use the `load_settings` function to load the data from the config-file.

**Comment by covrig** [comment]
Any update with this? It would be really nice to have. Thanks.

**Comment by danielperna84** [comment]
@sytone hasn't yet included my change-requests. As soon as he does I will merge his changes.

**Comment by covrig** [comment]
Considering that a lot (if not most) of the files shouldn't be edited, I think some filters are a must have feature. In my case more than 70% of the files, I never touch. Let's hope he responds. Thanks.

**Comment by danielperna84** [comment]
It actually depends. Since I have the configurator I use it to modify all kinds of files on various systems. I consider it more as a browser-based vim-editor that spares me from SSHing into all the machines. :)
If he does not respond I'll do it. But I want to give him the chance to have his work officially included in the commit-history, along with being a contributor. :)

**Comment by covrig** [comment]
I agree with your point of view and I am also doing this. However, some filters would be nice no matter what (considering that the tool is integrated in HASS and most people will use it to edit only YAML configurations files). 
There are all sort of files that I simply don't edit from the HASS interface. Better open a terminal and work there.
Thanks again.

**Comment by sytone** [comment]
hey, will get back today. Been on holidays :)

**Comment by sytone** [comment]
all updated, please review.

**Comment by danielperna84** [comment]
Add the empty `IGNORE_PATTERN` to the default settings.conf and we're good to go. :)

**Pull request merged**
